# Generated by Django 3.1.3 on 2020-12-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0002_auto_20201203_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastaction',
            name='date_action',
            field=models.DateField(blank=True, null=True),
        ),
    ]
