# Generated by Django 3.1.3 on 2020-12-03 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_directory', models.CharField(max_length=50)),
                ('size_directory', models.PositiveIntegerField()),
                ('created_date', models.DateField(blank=True, null=True)),
                ('changed_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('download_date', models.DateField(blank=True, null=True)),
                ('pathDestination', models.CharField(default='/', max_length=256)),
                ('pathSource', models.CharField(max_length=256)),
                ('directories', models.ManyToManyField(related_name='_directory_directories_+', to='filesApp.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('type_file', models.CharField(max_length=5)),
                ('id_file', models.CharField(max_length=128)),
                ('size_file', models.PositiveIntegerField()),
                ('seek_file', models.PositiveIntegerField()),
                ('pathDestination', models.CharField(default='/', max_length=256)),
                ('pathSource', models.CharField(max_length=256)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('changed_date', models.DateField(blank=True, null=True)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('download_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_action', models.CharField(choices=[('up', 'upload'), ('down', 'download')], default='up', max_length=4)),
                ('is_end_action', models.BooleanField(default=True)),
                ('counter', models.PositiveIntegerField()),
                ('object_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesApp.file')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('last_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesApp.lastaction')),
                ('root_directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesApp.directory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_to_download', models.ManyToManyField(related_name='download', to=settings.AUTH_USER_MODEL)),
                ('permission_to_read', models.ManyToManyField(related_name='read', to=settings.AUTH_USER_MODEL)),
                ('permission_to_share', models.ManyToManyField(related_name='share', to=settings.AUTH_USER_MODEL)),
                ('permission_to_view', models.ManyToManyField(related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='permission_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesApp.permission'),
        ),
        migrations.AddField(
            model_name='file',
            name='user_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='files',
            field=models.ManyToManyField(related_name='files', to='filesApp.File'),
        ),
        migrations.AddField(
            model_name='directory',
            name='permission_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesApp.permission'),
        ),
        migrations.AddField(
            model_name='directory',
            name='user_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
