# Generated by Django 3.1.3 on 2021-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0008_auto_20201211_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='id_directory',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
