# Generated by Django 3.1.3 on 2020-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0007_auto_20201211_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='directories',
            field=models.ManyToManyField(related_name='directoriesList', to='filesApp.Directory'),
        ),
    ]
